// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfdcndrzdkfopwsqrnpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZGNuZHJ6ZGtmb3B3c3FybnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDE4NDYsImV4cCI6MjA2OTQ3Nzg0Nn0.0xP7jxW7osVmMaZpu4Kg_aZ1k7Uz3hxXPD-Xm5coZzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});